---
- hosts: proxy_nodes
  become: yes
  vars:
    domain: jkan2.longhorn.pl
    app1_external_ip: 172.31.22.4
    app2_external_ip: 172.31.22.4
  tasks:
    - include_tasks: tasks/prepareProxy.yml
- hosts: application_nodes
  become: yes
  vars:
    jar_location: /home/ec2-user/environment/200243/ostatnia/template/jar.jar
    app_location: /opt/carrental/carrental.jar
    app_user: carrental
    telegraf_url: https://dl.influxdata.com/telegraf/releases/telegraf-1.8.3-1.x86_64.rpm
    metrics_storage_ip: 172.31.27.194
  tasks:
    - include_tasks: tasks/prepareApplication.yml
    - include_tasks: tasks/prepareTelegraf.yml
- hosts: metrics_node
  become: yes
  vars:
   influx_url: https://dl.influxdata.com/influxdb/releases/influxdb-1.7.1.x86_64.rpm
   grafana_url: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-5.3.4-1.x86_64.rpm
   metrics_storage_ip: 54.93.223.65
   metrics_private_ip: 172.31.27.194
  tasks:
    - include_tasks: tasks/prepareInflux.yml
    - include_tasks: tasks/prepareGraphana.yml