---
    - name: "install jre"
      yum:
        name: java-1.8.0-openjdk
        state: present
    - name: "create path"
      file:
        path: /opt/carrental
        state: directory
    - name: "copy .jar to remote machine"
      copy:
        src: "{{jar_location}}"
        dest: "{{app_location}}"
    - name: "create user for service"
      user:
        name: "{{app_user}}"
    - name: "prepare db"
      include_tasks: tasks/prepareDB.yml
    - name: "copy systemd config"
      template:
        src: template/car.service
        dest: /etc/systemd/system/car.service
    - name: "reload service"
      systemd:
        daemon_reload: yes
    - name: "start app"
      service:
        name: car
        state: restarted